"""Updated tables

Revision ID: 3c5452428d06
Revises: deab099675b2
Create Date: 2023-12-27 20:34:59.922972

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3c5452428d06'
down_revision: Union[str, None] = 'deab099675b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'master_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('order', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('vehicle', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('order', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('order', 'master_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
