"""add vehicle and order

Revision ID: deab099675b2
Revises: 75348240c824
Create Date: 2023-12-22 19:29:45.314210

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from fastapi_users_db_sqlalchemy import GUID

# revision identifiers, used by Alembic.
revision: str = 'deab099675b2'
down_revision: Union[str, None] = '75348240c824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('license_plate', sa.String(length=10), nullable=True),
    sa.Column('category',
              sa.Enum('car', 'truck', 'bus', 'motorcycle', 'other', name='vehicle_category'), nullable=False,
              ),
    sa.Column('VIN', sa.String(length=17), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('client_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('VIN'),
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('open', 'done', 'canceled', name='order_status'), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('master_id', GUID(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('client_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['master_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
